### PR TITLE
Obj-C tracker release 0.9.0

### PR DESCRIPTION
**Pull request by mhadam**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Hey @mhadam - a new release which deserves its own blog post (as this one does) should not be a patch release - it should at the least be a minor release:

0.9.0

Can you update everything accordingly?

**Comment by mhadam** [comment]
Got it - updated.

**Comment by alexanderdean** [comment]
Hey @mhadam - nudge on this. The 0.9.0 has been released, you need to get the docs ready and update the blog post links ^^.

**Comment by mhadam** [comment]
This should be clear to go now

**Pull request merged**
