### PR TITLE
Mnrq 573 princing

### PR DESCRIPTION
**Pull request by jorgemgoncalves**
This PR places the pricing table back on Snowplow Insights #573.

### CODE REVIEW

**Comment by jorgemgoncalves** [comment]
Hi @Mandelliant, this is that other PR that needs your assistance. Sorry...

**Comment by Mandelliant** [comment]
@jorgemgoncalves no trouble! Do you need me to merge onto QA once the conflicts are resolved?

**Comment by Mandelliant** [comment]
just needs new text from @yalisassoon

**Comment by jorgemgoncalves** [comment]
Created new clean branch for this issue.

**Pull request closed without merging**
