### PR TITLE
Blog/miken

### PR DESCRIPTION
**Pull request by jorgemgoncalves**

### CODE REVIEW

**Comment by mikenem** [comment]
Hi @jorgemgoncalves it seems like my blog post was merged successfully, but when actually trying to go to https://next.snowplowanalytics.com/blog/2019/03/18/how-many-visitors-block-your-tracking, it says page not found.

Bizarre that on the /blog page it is listed at the top. 

When checking the files, the .html was created but the _posts/2019-03-18-.... folder with index.md are not there.

Any idea what's going on?

**Comment by jorgemgoncalves** [comment]
Hi Mike,

I'm trying to figure what can be happening, locally it shows up correctly.

I'll post it online as soon as everything is ok.

Best regards,
Jorge.

*JORGE GONÇALVES*

DIGITAL MARKETING MANAGER

(+351) 912 640 757 . skype: jorge.goncalves.86

www.monarqa.com



Mike Nemirovsky <notifications@github.com> escreveu no dia quinta,
21/03/2019 à(s) 11:14:

**Comment by mikenem** [comment]
Ok thanks Jorge! Let me know if you need anything from me.

**Comment by jorgemgoncalves** [comment]
Hi Mike,

I've added a / to the end of the URL and it shows up in Next!

I've created a merge of branches to push online that include your blog
post.

I will put it online as soons as I get the OK from Franciska.

Best regards,
Jorge.

*JORGE GONÇALVES*

DIGITAL MARKETING MANAGER

(+351) 912 640 757 . skype: jorge.goncalves.86

www.monarqa.com



Mike Nemirovsky <notifications@github.com> escreveu no dia quinta,
21/03/2019 à(s) 11:35:

**Comment by mikenem** [comment]
Ok great thanks!

**Pull request merged**
