### PR TITLE
R108 blogpost

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
@alexanderdean could you have a look here too? thanks :+1:

**Comment by alexanderdean** [comment]
@BenFradet I am hazy on the relationship between:

* 1.1 Encrypting S3 buckets, and
* 1.2.1 At rest encryption on S3

Can you clarify? Either in this thread or in the post is fine.

**Comment by alexanderdean** [comment]
nudge @BenFradet

**Comment by BenFradet** [comment]
>1.1 Encrypting S3 buckets, and

is for the buckets we interact with with s3-dist-cp

>1.2.1 At rest encryption on S3

is for the buckets we would interact with directly from EMR through EMRFS, I'll specify that we don't use it at the moment

**Comment by BenFradet** [comment]
Agreed it was a terrible explanation, tried to overhaul it with a better example

**Comment by alexanderdean** [comment]
Good to go from me now.

**Comment by Mandelliant** [comment]
Good to go from me, @BenFradet let me know when the release notes and config.yml are ready

**Comment by BenFradet** [comment]
that'll be tomorrow morning

**Comment by BenFradet** [comment]
good to go from my side, ping me once this is out :+1:

**Pull request merged**
