### PR TITLE
Iglu R10 and RDB R30 blog posts

### PR DESCRIPTION
**Pull request by Mandelliant**

### CODE REVIEW

**Comment by Mandelliant** [comment]
Confirmed lead gen forms sending to pardot and salesforce

@chuwy ping me when the assets are published and we'll go live

**Comment by alexanderdean** [comment]
@chuwy what's the hold-up here?

**Comment by chuwy** [comment]
Nothing is blocking. Assets were published last week.

**Comment by Mandelliant** [comment]
@chuwy apologies, 'assets' wasn't the right word - I just need the release notes url for RDB R30

**Comment by Mandelliant** [comment]
confirmed lead forms unaffected

**Pull request merged**
