### PR TITLE
Posts/snowplow r102

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by Mandelliant** [comment]
Will review!

**Comment by Mandelliant** [comment]
Can someone confirm the grammar in the sentence:

> To improve the architecture described above, we can embrace Snowplow S3 Loader using single Stream Enrich to produce enriched data for the S3 sink.

I want to make sure I'm referring to S3 sink correctly.

**Comment by alexanderdean** [comment]
I haven't finished going through this @chuwy, but already some feedback:

* The upgrade section is insufficient. You don't mention the removal of the raw section, nor the fact that enriched.good is still used, and enriched.bad and enriched.errors are *not* still used. Plus this is inconsistent: why do we remove raw from the config.yml but not enriched.bad and errors?
* You link to the sample config.yml, but this doesn't show a meaningful example of this config. You should add a new config.yml into the repo which provides a proper template for this setup, as it's now the official setup for our realtime pipeline...

**Comment by Mandelliant** [comment]
@alexanderdean other than your feedback, the post looks good from my point of view. Once it's updated, I'll do another pass.

**Comment by chuwy** [comment]
Hey @alexanderdean, I didn't mention removal of `enriched.bad`, `enriched.errors` etc, because EmrEtlRunner still has them in contracts. I removed from contracts only `raw` just because decided it is most important to highlight that we're not using it. 

Assuming we still want to make this entirely different `config.yml`, so I'll remove them and will publish rc4 with these changes.

**Comment by alexanderdean** [comment]
Thanks @chuwy - I've reviewed it now and made quite a lot of additions and changes. It's ready to go from me. If you can get the rc4s onto canaries on Monday that would be great.

**Comment by alexanderdean** [comment]
Is this ready for releasing Tuesday @chuwy ?

**Comment by chuwy** [comment]
Yep, this is ready for release. I added one note about importance of deleting data from `enriched.good` in stream mode.

**Comment by Mandelliant** [comment]
@alexanderdean @chuwy I can publish this today

**Comment by alexanderdean** [comment]
Awesome! @chuwy please remove the embargo when the release is on its way out...

**Comment by chuwy** [comment]
Great. Will do.

**Pull request merged**
