### PR TITLE
Snowflake DB release post

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by yalisassoon** [comment]
@alexanderdean I've sexed up the post: https://github.com/snowplow/snowplowanalytics.com/pull/405/commits/02814477b03e7da064253f9f6c24f892521af568

I'll do a final check before we push live. Let me know when we can do that!

**Comment by Mandelliant** [comment]
Just wanted to make sure that when we go live we'll have the snowplow incubator links for snowflake loader in place- they're still 404'ing at this point (sorry if I missed that in the discussion somewhere).

Otherwise this post looks great to go!

**Comment by alexanderdean** [comment]
Okay I've done some further edits. I think we are getting there. The only thing I am still unsure of is the Dataflow Runner playbook. I'm not convinced by these parts:

```
               "--base64",
               "--config",
               "{{.config}}",
               "--resolver",
               "{{.resolver}}"
```

It would be more normal to use the `base64Ffile` function, like so:

```
"{{"{{base64File \"/my-file.json\"}}"}}"
```

**Comment by chuwy** [comment]
I've updated configs according to latest fixes. But decided to not add full secure approach to setup here, as it would at least double the "Setup" section - instead @Mandelliant advised to just mention that more secure approach is possible and provide link to documentation (or discourse). Role-based (secure) approach is on wiki now.

**Comment by alexanderdean** [comment]
Why was this merged? The release green-light hasn't been given. Please revert @Mandelliant urgently.

**Pull request merged**
