### PR TITLE
R96 Zeugma

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
the fact that you can choose between nsq, kinesis or kafka for the ssc actually is a breaking change, I'll modify accordingly

**Comment by alexanderdean** [comment]
Right - per our convo yesterday @BenFradet , please add a section into the upgrade section explaining the minimum viable config changes for a Kinesis or Kafka user.

**Comment by BenFradet** [comment]
isn't [this](https://github.com/snowplow/snowplowanalytics.com/pull/371/files#diff-861ac16e5c50eacf7c5482d3b8033126R196-R240) (up to line 240) sufficient?

**Comment by alexanderdean** [comment]
Looks good, have just changed the ordering a bit. Good to go from my end.

**Comment by BenFradet** [comment]
@yalisassoon can you help us get this in?

**Comment by yalisassoon** [comment]
@BenFradet can you please make this pull request to next.snowplowanalytics.com please? Thanks

**Comment by BenFradet** [comment]
@yalisassoon done 👍

**Pull request merged**
