### PR TITLE
SQL Runner 0.7.0

### PR DESCRIPTION
**Pull request by mhadam**
First draft done - needs some links, examples and some edits.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Please @ me when ready for next pass.

**Comment by mhadam** [comment]
Updates done @alexanderdean

**Comment by alexanderdean** [comment]
Can you make that change please @mhadam ?

**Comment by alexanderdean** [comment]
Can we get your green tick @Mandelliant  ?

**Comment by mhadam** [comment]
I've released it, added a Github release note, and made a Discourse thread.

Re: the blog post, it looks like `Using Consul only for locking` already has its own section. Let me know if I can help with anything.

**Comment by alexanderdean** [comment]
I think @Mandelliant was saying that it should be merged (but hasn't yet).

**Comment by Mandelliant** [comment]
@alexanderdean correct. I'm pushing that change now, but it's otherwise good to go once the embargo is lifted

**Comment by Mandelliant** [comment]
@mhadam @alexanderdean good to go from my end

**Comment by alexanderdean** [comment]
Thanks so much! I removed the embargo.

**Pull request merged**
