### PR TITLE
Iglu R7 Treskilling Yellow blog post & Add Oguzhan as author

### PR DESCRIPTION
**Pull request by oguzhanunlu**
Blog post for R7

@alexanderdean @chuwy

### CODE REVIEW

**Comment by alexanderdean** [comment]
@chuwy you okay to do first pass?

**Comment by chuwy** [comment]
Yep, will do after finishing QA.

**Comment by alexanderdean** [comment]
Please add me as a reviewer when ready @chuwy

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/snowplowanalytics.com/pull/444

**Pull request closed without merging**
