### PR TITLE
Added R104 blog post

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by chuwy** [comment]
Hey @alexanderdean, @Mandelliant did you have a chance to look at it?

**Comment by alexanderdean** [comment]
I didn't yet but I will try and read it later today!

**Comment by Mandelliant** [comment]
@chuwy @alexanderdean there are three urls missing from the bottom of the post:
- Snowflake Analytics
- Google Cloud Dataflow
- Apache Beam APIs

Where would you like those to point? I'll add them in right now.

**Comment by chuwy** [comment]
Hey @Mandelliant!

1. https://www.snowflake.net/
2. https://cloud.google.com/dataflow/
3. https://beam.apache.org/

**Comment by Mandelliant** [comment]
@chuwy awesome, thanks!

**Pull request merged**
