### PR TITLE
GetNinjas case study & other fixes

### PR DESCRIPTION
**Pull request by Mandelliant**
Publishes GetNinjas case study, fixes contact and community pages

### CODE REVIEW

**Comment by Mandelliant** [comment]
@jorgemgoncalves for some reason when I build locally, the text beneath the form on the Contact page renders fine:

screen shot 2018-10-10 at 6 44 32 pm

but on next it's still warped:

screen shot 2018-10-10 at 6 46 45 pm

Any ideas?

**Comment by jorgemgoncalves** [comment]
Hi Anthony,

That doesn't seem right. Are you merging each branch individually?

*JORGE GONÇALVES*
DIGITAL MARKETING MANAGER
(+351) 912 640 757 . skype: jorge.goncalves.86
www.monarqa.com



Anthony <notifications@github.com> escreveu no dia quarta, 10/10/2018 à(s)
23:47:

**Comment by Mandelliant** [comment]
Ah Jorge that makes sense, thank you for pointing that out!

**Comment by Mandelliant** [comment]
Confirmed lead gen forms unaffected

**Pull request merged**
