### PR TITLE
Added blog post for Snowplow S3 Loader 0.6.0 release

### PR DESCRIPTION
**Pull request by aldemirenes**

### CODE REVIEW

**Comment by alexanderdean** [comment]
It doesn't look like @BenFradet has done any editing on this post? Not sure why it has been approved un-edited.

**Comment by alexanderdean** [comment]
Closing in favor of https://github.com/snowplow/snowplowanalytics.com/pull/276

**Comment by BenFradet** [comment]
I did, the commits were just squashed together in order to keep the history clean.

**Comment by alexanderdean** [comment]
Okay np, I am working through the post now too.

**Comment by BenFradet** [comment]
the PR needs to be open against the `next.snowplowanalytics.com` branch btw

**Pull request closed without merging**
