### PR TITLE
R109 blogpost

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
>Externalize the file used for the user agent parser enrichment - neat idea but I can't see any upgrading guidance, and I am hazy on whether we are committing to providing the latest file, on S3, for users
The upgrading section seems to be placeholders

Yes, I haven't done any writing on the upgrade process yet.

>1.3 CloudFront updates - this functionality will only make sense in a batch pipeline that is processing CloudFront access logs, but it is included in an RT release?
Need to add notes to relevant sub-sections that specified new features will be coming to batch in a couple of releases' time

yes, because of that I was thinking of having a spark enrich release anyway

**Comment by Mandelliant** [comment]
After finishing my first pass review, the community development aspect of this release is really cool and I’d like to feature it a bit more prominently. How big a part of R109 is the community element? Was it planned from the start to have so many contributors and then use it as an opportunity to improve developer relations?

> The Scala Stream Collector now supports `HEAD` requests wherever `GET` requests were supported previously.

Can we provide an example of why you would want to do this or why we added this functionality? Who is going to read this sentence and say, "Finally!"

**Comment by alexanderdean** [comment]
Right, I have completed my edits - removing anything that doesn't relate to the RT pipeline which I understand this release to be exclusively updating (so I stripped out the whole CloudFront access log section).

@BenFradet please have a full re-read through and check all my additions.

Note that I am still pretty confused by the underlying release - see my comment here:

https://github.com/snowplow/snowplow/pull/3853#issuecomment-414018001

But I am giving it the green tick on the assumption the stray Spark Enrich commits will be removed from the code...

**Comment by BenFradet** [comment]
@alexanderdean updated in 27f9c48

**Comment by alexanderdean** [comment]
Good to go from me

**Comment by Mandelliant** [comment]
@alexanderdean thanks, I'll do one final pass and coordinate with @BenFradet for publishing

**Pull request merged**
