### PR TITLE
BigQuery initial release post

### PR DESCRIPTION
**Pull request by chuwy**
Hey @alexanderdean, @Mandelliant! Sorry for delay - this is probably my toughest post so far. Looking for your feedback.

### CODE REVIEW

**Comment by Mandelliant** [comment]
@chuwy looking forward to reading and reviewing this one!

**Comment by alexanderdean** [comment]
Hey @chuwy - I've reviewed this now. It's a pretty formidable post, well done.

A few things:

* It's crying out for a technical diagram, showing how the Loader, Mutator and all the topics all inter-relate
* The documentation links go to an empty wiki right now. That needs to be fixed ASAP
* I was surprised that the race condition inherent in the decoupled Mutator-Loader design wasn't called out as something we are working on fixing in the roadmap. It's not great for the BigQuery Loader to be inherently a little bit lossy
* I was surprised that the lack of a partitioning strategy wasn't called out in the roadmap as something we are working on

I'll assign this to @yalisassoon now for the Product review.

**Comment by alexanderdean** [comment]
Nudge @chuwy - can you review my last feedback and action?

**Comment by alexanderdean** [comment]
What is the hold-up on this one @chuwy ?

**Comment by chuwy** [comment]
Nothing is holding it. I'm on my way.

**Comment by chuwy** [comment]
@yalisassoon, @Mandelliant, just in case - @alexanderdean's feedback has been addressed and this is ready for final review.

**Comment by yalisassoon** [comment]
@chewy this release post is absolutely excellent. I've made some minor tweaks. From my perspective this is good to go. @Mandelliant would be good if you could cast your eye over it.

**Comment by Mandelliant** [comment]
@yalisassoon will be reviewing tomorrow

**Comment by alexanderdean** [comment]
Nudge @Mandelliant

**Pull request merged**
