### PR TITLE
Add RDB Loader R28 post

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by chuwy** [comment]
Hey @BenFradet, do you want to add a line about RDB Shredder change?

**Comment by BenFradet** [comment]
yup, will do :+1:

**Comment by alexanderdean** [comment]
I've finished my review! Now for QA...

**Comment by chuwy** [comment]
Updated date and renamed release to R28 as per discussion https://github.com/snowplow/snowplow-rdb-loader/pull/46#issuecomment-336098457

**Comment by chuwy** [comment]
Hey @yalisassoon, could you please take care of it along with @BenFradet's https://github.com/snowplow/snowplowanalytics.com/pull/313. These are coupled releases and we want to announce them at one moment.

**Pull request merged**
