### PR TITLE
Release/r106 acropolis

### PR DESCRIPTION
**Pull request by knservis**
This is a draft as I need to update:

- [x] bintray URL
- [x] Roadmap
- [x] IAB link
- [ ] Piinguin mini post link
- [ ] (Possibly add a link from `other enhancements` to https://github.com/snowplow/snowplowanalytics.com/pull/751)

### CODE REVIEW

**Comment by Mandelliant** [comment]
@knservis need the following links:

- [dataflow]:
- [gdpr-web]:
- [snowflake-analytics]:
- [iab-data]:
- [beam]:

**Comment by yalisassoon** [comment]
Hey @Mandelliant @knservis - in this post we need to give a brief explanation of the Piinguin project and link through to that release post _before_ we dive into the intricacies of the new stream of events. Otherwise we're giving a very clear, very detailed description of the mechanics and structure of the stream, with no context of why we've created it or how it's used, which makes it totally baffling for a reader who hasn't heard of Piinguin prior.

**Comment by knservis** [comment]
@Mandelliant I added the links except IAB (not sure what that its)

**Comment by knservis** [comment]
@yalisassoon So a subheading under `1. Overview of the new PII-related capabilities` called `Related projects` where i write one or two sentences about piinguin and relay and then link to the new "simple post" about piinguin?

**Comment by knservis** [comment]
@yalisassoon @Mandelliant What I understood is that you will have a Piinguin post introducing it. Is that correct? I have added a subsection in overview introducing and linking it but left the link empty

**Pull request merged**
