### PR TITLE
Release Iglu R7

### PR DESCRIPTION
**Pull request by chuwy**
https://github.com/snowplow/iglu/pull/280 branched from `next`

### CODE REVIEW

**Comment by alexanderdean** [comment]
Please add me as reviewer when this is ready to go!

**Comment by chuwy** [comment]
Done.

**Comment by alexanderdean** [comment]
This is ready from me. It looks like there's some kind of conflict around the authors file.

A couple of notes:

* Refreshments in English means "light snacks or drinks", not updated software features
* I removed the whole section 1. It belongs in the RFC for schema inference, not in the release post for R7. The text is still in the git history for future use

**Comment by chuwy** [comment]
Nice. Conflict resolved. Could you please merge it? Me and @oguzhanunlu will publish the release right after that.

**Comment by alexanderdean** [comment]
Merged! I'll ask Anthony to publish to master once he's taken a look.

**Pull request merged**
