### PR TITLE
R93 post

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @BenFradet - I'll do a detailed review soon, but one addition please - could you make sure to call out the more permissive URL parsing inside of Common Enrich? Just needs a sentence somewhere

**Comment by BenFradet** [comment]
@alexanderdean yes, it's [here](https://github.com/snowplow/snowplowanalytics.com/pull/296/files#diff-42869b6c3473cb80d3d12d2507636a36R65) it felt a bit awkward since I didn't know if it deserved a dedicated section...

**Comment by alexanderdean** [comment]
Thanks @BenFradet . This is good to go from my side.

**Comment by BenFradet** [comment]
@yalisassoon could you help us get this merged in?

**Comment by yalisassoon** [comment]
Hey @BenFradet - can you update the PR so that it's into next.snowplowanalytics.com? I'll then merge it there and then merge that into master.

Thanks!

**Comment by BenFradet** [comment]
@yalisassoon woops my bad, done :+1:

**Pull request merged**
