### PR TITLE
Piinguin release

### PR DESCRIPTION
**Pull request by knservis**
Not yet read as: 

- [ ] ~~Need to check links when bintray is ready~~
- [x] Updated links
- [x] Add IAM policies
- [x] Add DynamoDB table creation instructions
- [x] Remove release link from help section (?? it is not in the help section)
- [x] Add wiki link to help section
- [x] Add smoke test section after section 4

### CODE REVIEW

**Comment by knservis** [comment]
@jbeemster Can you please have a look that it all makes sense? I am going to add the IAM policies now

**Comment by Mandelliant** [comment]
@knservis can I switch this PR to merge into Next instead of Master?

**Comment by alexanderdean** [comment]
That should be fine @Mandelliant

**Comment by Mandelliant** [comment]
Thanks, @alexanderdean. This is high on my list for next week (week of June 4).

**Comment by yalisassoon** [comment]
HI @Mandelliant @knservis @alexanderdean - just had a first read of this having looked at the r106 release post.

Like the r106 post, this post gives lots of technical details about the workings of Piinguin with very limited explanation of why this functionality has been built and the business value it delivers. I think that makes this a hard post to read - even if you're an engineer, you need the context of what this is supposed to do before you have a desire to understand how it works.

Based on that my recommendation is that @Mandelliant and I work up a third post that is published alongside both of these, that explains the thinking and vision behind Piinguin. This will need to be scheduled for the next marketing sprint that kicks off next week.

Does that sound all right? It means this would go out next week. 

Many thanks,


Yali

**Comment by Mandelliant** [comment]
@knservis we're gearing up to publish this: do you have an update on your two checkbox items?

**Comment by knservis** [comment]
@Mandelliant  I will check it today.

**Comment by knservis** [comment]
@Mandelliant The IAM policy is there on the document. The bintray links are not because we havent done a release yet. When is the release happening?

**Comment by alexanderdean** [comment]
Hey @knservis - the post is good, sorry for the delay in reviewing it. Just three things:

1. DynamoDB table - I am hazy on the setup process for this. Is it auto-created by a component? If so, which component and when? If not, can you add setup instructions to the blog post

2. Getting help section - it's meaningless to reference release notes which will just say "initial release". Much better to link to the relevant wiki pages in the Piinguin wiki. Please update

3. Missing "smoke test" section - after the setup is complete (section 4), it would be nice to add a section that briefly recaps what is now running and shows a screenshot of the now-nicely-populated DynamoDB table. This answers the classic "have I really set this thing up correctly?" question that all users of open-source projects experience

Please ping me once these three things have been added to the post...

**Comment by knservis** [comment]
hey @alexanderdean I added that. 

Specifically on 2. the release notes are only mentioned in the intro, not in the help section. Maybe in the initial release notes we can add bullet point of the features.

**Comment by alexanderdean** [comment]
Thanks @knservis, post is good to go from me. Don't worry about the software release notes being empty - that's how all our v0.1.0s start...

**Pull request merged**
