### PR TITLE
Release 101 blog post

### PR DESCRIPTION
**Pull request by BenFradet**
- [ ] date
- [x] vbox died on me so I haven't been able to generate it yet...
- [x] links to the wiki
- [x] jmx
- [x] mention kafka 101 bump

### CODE REVIEW

**Comment by BenFradet** [comment]
@alexanderdean updated :+1:

**Comment by BenFradet** [comment]
@Mandelliant @yalisassoon do you have an ETA on when this would get in so we can coordinate our release efforts? Thanks.

**Comment by yalisassoon** [comment]
I've done a first pass and it looks great! Want to quickly check it over with fresh eyes in the morning.
Thanks @BenFradet ! Super exciting...

**Comment by alexanderdean** [comment]
Any update @yalisassoon ?

**Comment by Mandelliant** [comment]
@alexanderdean @yalisassoon I'm reviewing now as well!

**Comment by Mandelliant** [comment]
Content is all good, great job @BenFradet! I want to confirm that we're waiting on this article to be pushed to next/ready to publish for the following links: bintray stream collector, sample config.hocon, bintray stream enrich, release notes. 

The layout for the artifacts tables for Stream Collector and Stream Enrich were not rendering cleanly in my local version- trying a quick adjustment.

**Pull request merged**
