### PR TITLE
Add blog post for the cloud storage loader

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by yalisassoon** [comment]
@BenFradet looks good to me - I've made some changes - mostly to the first paragraph that I hope make it easier to understand for someone who's coming to the post cold. (And maybe hasn't followed our progress on GCP so closely.)

@Mandelliant would you mind giving it a quick once over?

**Comment by alexanderdean** [comment]
Awesome, hopefully @Mandelliant can ship this as part of Website Wednesday.

**Comment by yalisassoon** [comment]
I don't think we're ready to release today - Joao and Ben working on deployment... This should go out next Wednesday

**Comment by BenFradet** [comment]
We've completed deployment yesterday night 👍 , however this won't be released today, probably Friday

**Comment by franciskadfyi** [comment]
to minimise confusion on the marketing front, it would be great if @yalisassoon could update us when it's *ready* to be reviewed and released. then I will be sure to coordinate accordingly in JIRA.

**Comment by BenFradet** [comment]
project has been released ping me when you release the blog post :+1:

**Comment by BenFradet** [comment]
apparently this didn't make it into Wednesday's blog post release cycle?

**Comment by franciskadfyi** [comment]
sorry that wasn't communicated @BenFradet, we're planning to release everything on Monday: marketing post, storage loader and BigQuery loader (just waiting for final go on the BigQuery loader)

**Pull request merged**
