### PR TITLE
Iglu R8 blog post

### PR DESCRIPTION
**Pull request by oguzhanunlu**
@chuwy This is an initial draft for Iglu R8 blog post.

### CODE REVIEW

**Comment by chuwy** [comment]
Thanks @oguzhanunlu. Will have a look.

**Comment by alexanderdean** [comment]
Please assign me to review when you are wrapped @chuwy

**Comment by chuwy** [comment]
Superseded by https://github.com/snowplow/snowplowanalytics.com/pull/499.

Hey @alexanderdean, can we give @oguzhanunlu permission to create branches in this repository? (assuming this is why PR was created from his fork?)

**Comment by alexanderdean** [comment]
> Hey @alexanderdean, can we give @oguzhanunlu permission to create branches in this repository?

Done!

**Pull request closed without merging**
