### PR TITLE
Release Iglu R8

### PR DESCRIPTION
**Pull request by chuwy**
From https://github.com/snowplow/snowplowanalytics.com/pull/495

### CODE REVIEW

**Comment by chuwy** [comment]
Hm, do we still create PRs against `next.snowplowanalytics.com`? Why then there's additions to `authors.yml`?

**Comment by Mandelliant** [comment]
@chuwy yeah, PRs should be against `next.snowplowanalytics.com`. I'm not positive why there's a conflict with `authors.yml` but I can take a look. Let me know if you need any help.

**Comment by chuwy** [comment]
Hey @alexanderdean, this is ready from me.

**Comment by chuwy** [comment]
Hey @alexanderdean I think I addressed your points, but "Dealing with inconsistent schema versions" section started to grow infinitely when I tried to put it in a way you proposed - now sure what parts of this lengthy explanation can be removed.

**Comment by alexanderdean** [comment]
Thanks @chuwy - I've done a final review on it and done some pruning :-)

**Pull request merged**
