### PR TITLE
Three blog updates plus other fixes

### PR DESCRIPTION
**Pull request by Mandelliant**

### CODE REVIEW

**Comment by Mandelliant** [comment]
confirmed lead gen forms unaffected

**Comment by alexanderdean** [comment]
Believe this is still under embargo pending testing. I will review it later this weekend.

**Comment by Mandelliant** [comment]
@alexanderdean great, thank you! @franciskadfyi will coordinate publishing with @knservis this upcoming week (provided the embargo is lifted)

**Comment by franciskadfyi** [comment]
Hey @alexanderdean, I see that this is still under embargo. Do you have an idea of when this will be lifted? I am helping out Anthony this week while he's enjoying the Scottish nature.

**Comment by alexanderdean** [comment]
@knservis - how is the testing going on this?

**Comment by knservis** [comment]
@alexanderdean There is an issue of reading the criteria from S3 in some cases (it works locally but EMR is unhappy sometimes, for some reason) using vfs. I am fixing that today.

**Comment by alexanderdean** [comment]
Okay @knservis - keep us posted!

**Comment by knservis** [comment]
@alexanderdean Actually I just fixed the vfs issue. It's gtg now

**Comment by franciskadfyi** [comment]
@knservis final testing is done as well? If so, I'll merge today.

**Comment by knservis** [comment]
@franciskadfyi Test is successful. Go ahead and publish (please let me know so that I can also release the same day)

**Comment by alexanderdean** [comment]
I will review the post tonight.

**Comment by Mandelliant** [comment]
@alexanderdean confirming you're good for this to go live?

**Comment by alexanderdean** [comment]
Ready to go from me @Mandelliant, apologies for delay.

**Comment by Mandelliant** [comment]
Awesome, @alexanderdean, thank you!!

**Comment by Mandelliant** [comment]
Publishes:
- Right to be forgotten
- Objective C 0.9.0 
- Customer acquisition for marketplaces

Fixes:
- Website footer
- Snowplow Insights pricing table width

**Comment by Mandelliant** [comment]
confirmed lead gen forms unaffected

**Pull request merged**
